Dynamic bridge endpoint
GAIA-X4PLC-AAD/ssi-to-oidc-bridge pull request #34
Opened 2024-07-08 11:14 UTC by ilaydacansinkoc

2024-08-21 15:20 UTC, jfelixh requested changes
Overall, lots of good changes. But there are a couple of things I am not super happy about. Would love to get some input on my comments @ilaydacansinkoc, but no code changes required. I will do whatever changes after hearing your thoughts.

2024-08-21 17:06 UTC, ilaydacansinkoc commented on README.md
> +> and should have integer string values starting from 1, incrementing by 1 for each subsequent policy object. This helps us determine
**For the first comment:**

The `credentialId` helps to extract the correct claims from the correct policy.

I guess I added this when I tested a scenario when we want to extract same claims from the different type of VCs.
(2 VCs of different type but the field that we want to extract is the same: `$.credentialSubject.name`)

In practice, I think we can give unique string IDs again, but then we need to make sure that the constraints are evaluated correctly as well (`isValidConstraintFit`, and `resolveValue` functions). In these functions, I use `credentialId` to locate the correct VC to apply constraints. 

---

**For the second comment:**

It's required to be an integer-valued string. "1" or "2" for example.

2024-08-21 17:07 UTC, ilaydacansinkoc commented on README.md
> +> Altough the `type` field is an optional parameter, it needs to be
You might be right; I think this way: Each organization would have a certain type of VC, and the service provider would accept that type of VC.

The idea is similar to having registries so the verifier can know what credentials to accept.

But then we need to tell the code to apply the correct policy to the correct type of VC.

2024-08-21 17:09 UTC, ilaydacansinkoc commented on vclogin/config/loginPolicy.ts
Do you mean the async await use?

You might be right, but it caused some issues while performing the first login: It couldn't read the policy file when it supposed to, and therefore getting errors in the wallet app.

2024-08-21 17:12 UTC, ilaydacansinkoc commented on test_client.sh
Right, maybe adding a description to the readme on how to configure it instead would be a better solution.

2024-08-21 17:17 UTC, ilaydacansinkoc commented on vclogin/middleware.ts
https://nextjs.org/docs/app/building-your-application/routing/middleware

This is basically a NextJS middleware that runs before a request is completed.
I am not sure if we can change the file name.

2024-08-21 17:17 UTC, ilaydacansinkoc commented on vclogin/lib/generatePresentationDefinition.ts
> +    name: "VC Login Service",
I am not sure why I changed this. I guess you can just use the other one as well.

2024-08-21 17:19 UTC, ilaydacansinkoc commented on vclogin/lib/generatePresentationDefinition.ts
> -        name: "Group " + expectation.credentialId,
I guess I removed it mistakenly

2024-08-21 17:21 UTC, ilaydacansinkoc commented on vclogin/pages/api/clientMetadata.ts
> -import { withLogging } from "@/middleware/logging";
No 😀

2024-08-23 15:57 UTC, jfelixh commented on vclogin/middleware.ts
Name is mandatory for built-in NextJS middleware system.

2024-10-28 08:33 UTC, jfelixh approved these changes

2024-10-28 10:09 UTC, jdsika commented
Why is the build not triggered? Can you confirm the build locally?

2024-10-28 12:30 UTC, jfelixh commented
> Why is the build not triggered? Can you confirm the build locally?

I have no idea. The normal build on Node 20.x works (locally and here). But the old built on 18.x, that we removed from the github action, is still showing up here. It was already removed in the last merged PR, since 18.x is pretty old and it should be sufficient to have the tests and build run on one Node version.

2024-10-28 13:12 UTC, jdsika approved these changes

2024-10-28 13:17 UTC, merged